# Copyright (c) 2017 Kichwa Coders Ltd.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html

FROM jonahkichwacoders/poky

RUN sudo apt-get update && \
	sudo apt-get install qemu -y && \
    sudo rm -rf /var/lib/apt/lists/*
